import React from 'react';
import firebase from 'firebase/app'; // Firebase 초기화 가져오기
import 'firebase/firestore'; // Firestore 서비스 가져오기
import './addLegodata.css'; // CSS 파일 추가

function AddLegoData() {
    // JSON 데이터 배열
    const taskData = [
        {
            "date": "2024-04-23",
            "userTeam": "IT전략기획팀",
            "userName": "김가인",
            "department": "사업부서",
            "projectName": "비대면",
            "categoriesName": "사업부서_검토_수정",
            "subcategoriesName": "상세_검토수정",
            "subsubcategoriesName": "상세_검토수정",
            "baseTime": "3",
            "spentTime": "3",
            "status": "진행중",
            "note": "암케어디지털통합플랫폼사업사업협약서수정및작성",
            "remainingTime": "0",
            "Uesrsid": "XJwp5I5AXb2GhK04cOVN"
        },
        {
            "date": "2024-04-23",
            "userTeam": "IT전략기획팀",
            "userName": "김가인",
            "department": "사업부서",
            "projectName": "비대면",
            "categoriesName": "회의운영",
            "subcategoriesName": "내부회의",
            "subsubcategoriesName": "회의진행(사업,협회,기타)",
            "baseTime": "2",
            "spentTime": "0.5",
            "status": "완료",
            "note": "비대면암센터실무자주간회의",
            "remainingTime": "1.5",
            "Uesrsid": "XJwp5I5AXb2GhK04cOVN"
        },
        {
            "date": "2024-04-25",
            "userTeam": "IT전략기획팀",
            "userName": "김가인",
            "department": "사업부서",
            "projectName": "비대면",
            "categoriesName": "회의운영",
            "subcategoriesName": "내부회의",
            "subsubcategoriesName": "회의자료작성(HWP)",
            "baseTime": "1",
            "spentTime": "6",
            "status": "진행중",
            "note": "아바엔터테인먼트소송건관련보완",
            "remainingTime": "-5",
            "Uesrsid": "XJwp5I5AXb2GhK04cOVN"
        },
        {
            "date": "2024-04-26",
            "userTeam": "IT전략기획팀",
            "userName": "김가인",
            "department": "사업부서",
            "projectName": "비대면",
            "categoriesName": "회의운영",
            "subcategoriesName": "내부회의",
            "subsubcategoriesName": "회의자료작성(PPT)",
            "baseTime": "3",
            "spentTime": "2",
            "status": "진행중",
            "note": "비대면0430전체회의발표ppt제작및수정",
            "remainingTime": "1",
            "Uesrsid": "XJwp5I5AXb2GhK04cOVN"
        },
        {
            "date": "2024-05-02",
            "userTeam": "IT전략기획팀",
            "userName": "김가인",
            "department": "사업부서",
            "projectName": "비대면",
            "categoriesName": "회의운영",
            "subcategoriesName": "내부회의",
            "subsubcategoriesName": "회의진행(사업,협회,기타)",
            "baseTime": "2",
            "spentTime": "1",
            "status": "완료",
            "note": "[비대면]업무진행사항브리핑(4월정기회의내용,사업비세금계산서,국립암센터요청사항)",
            "remainingTime": "1",
            "Uesrsid": "XJwp5I5AXb2GhK04cOVN"
        },
        {
            "date": "2024-05-02",
            "userTeam": "IT전략기획팀",
            "userName": "김가인",
            "department": "사업부서",
            "projectName": "비대면",
            "categoriesName": "사업부서_검토_수정",
            "subcategoriesName": "상세_검토수정",
            "subsubcategoriesName": "상세_검토수정",
            "baseTime": "3",
            "spentTime": "1",
            "status": "진행중",
            "note": "비대면입찰공고내용점검수정",
            "remainingTime": "2",
            "Uesrsid": "XJwp5I5AXb2GhK04cOVN"
        },
        {
            "date": "2024-05-02",
            "userTeam": "IT전략기획팀",
            "userName": "김가인",
            "department": "사업부서",
            "projectName": "비대면",
            "categoriesName": "회의운영",
            "subcategoriesName": "외부회의",
            "subsubcategoriesName": "회의진행(출장시출장이동시간포함)",
            "baseTime": "2",
            "spentTime": "0.5",
            "status": "완료",
            "note": "[비대면]갤러리(HART)산출물수정관련회의",
            "remainingTime": "1.5",
            "Uesrsid": "XJwp5I5AXb2GhK04cOVN"
        },
        {
            "date": "2024-05-03",
            "userTeam": "IT전략기획팀",
            "userName": "김가인",
            "department": "사업부서",
            "projectName": "비대면",
            "categoriesName": "사업부서_검토_수정",
            "subcategoriesName": "상세_검토수정",
            "subsubcategoriesName": "상세_검토수정",
            "baseTime": "3",
            "spentTime": "2",
            "status": "완료",
            "note": "[비대면]사전규격공개완료/제안요청서,공고문수정,검토",
            "remainingTime": "1",
            "Uesrsid": "XJwp5I5AXb2GhK04cOVN"
        },
        {
            "date": "2024-05-07",
            "userTeam": "IT전략기획팀",
            "userName": "김가인",
            "department": "사업부서",
            "projectName": "비대면",
            "categoriesName": "사업부서_검토_수정",
            "subcategoriesName": "상세_검토수정",
            "subsubcategoriesName": "상세_검토수정",
            "baseTime": "3",
            "spentTime": "1",
            "status": "진행중",
            "note": "[비대면]물품관리리스트지역암센터자료수집",
            "remainingTime": "2",
            "Uesrsid": "XJwp5I5AXb2GhK04cOVN"
        },
        {
            "date": "2024-05-07",
            "userTeam": "IT전략기획팀",
            "userName": "김가인",
            "department": "사업부서",
            "projectName": "비대면",
            "categoriesName": "회의운영",
            "subcategoriesName": "외부회의",
            "subsubcategoriesName": "회의진행(출장시출장이동시간포함)",
            "baseTime": "2",
            "spentTime": "1",
            "status": "진행중",
            "note": "[비대면]암센터실무자주간회의및검토",
            "remainingTime": "1",
            "Uesrsid": "XJwp5I5AXb2GhK04cOVN"
        },
        {
            "date": "2024-05-08",
            "userTeam": "IT전략기획팀",
            "userName": "김가인",
            "department": "사업부서",
            "projectName": "비대면",
            "categoriesName": "사업부서_검토_수정",
            "subcategoriesName": "타부서지원",
            "subsubcategoriesName": "타부서지원",
            "baseTime": "1",
            "spentTime": "6",
            "status": "완료",
            "note": "아바엔터테인먼트소송건관련사실조회서작성,본공고규격서수정",
            "remainingTime": "-5",
            "Uesrsid": "XJwp5I5AXb2GhK04cOVN"
        },
        {
            "date": "2024-05-09",
            "userTeam": "IT전략기획팀",
            "userName": "김가인",
            "department": "사업부서",
            "projectName": "비대면",
            "categoriesName": "회의운영",
            "subcategoriesName": "내부회의",
            "subsubcategoriesName": "회의진행(사업,협회,기타)",
            "baseTime": "2",
            "spentTime": "2",
            "status": "완료",
            "note": "[비대면]제안요청서최종수정회의/공고문수정,검토",
            "remainingTime": "0",
            "Uesrsid": "XJwp5I5AXb2GhK04cOVN"
        },
        {
            "date": "2024-05-09",
            "userTeam": "IT전략기획팀",
            "userName": "김가인",
            "department": "사업부서",
            "projectName": "비대면",
            "categoriesName": "사업부서_검토_수정",
            "subcategoriesName": "간단_검토수정",
            "subsubcategoriesName": "간단_검토수정",
            "baseTime": "1",
            "spentTime": "2",
            "status": "진행중",
            "note": "[비대면]지역암센터물품관리내용작성회신,문의사항응대",
            "remainingTime": "-1",
            "Uesrsid": "XJwp5I5AXb2GhK04cOVN"
        },
        {
            "date": "2024-05-10",
            "userTeam": "IT전략기획팀",
            "userName": "김가인",
            "department": "사업부서",
            "projectName": "비대면",
            "categoriesName": "사업부서_기타",
            "subcategoriesName": "타부서지원",
            "subsubcategoriesName": "타부서지원",
            "baseTime": "1",
            "spentTime": "6",
            "status": "진행중",
            "note": "[비대면]지역암센터물품관리내용작성회신,문의사항응대/협회및국립암센터물품관리내역요청/작성",
            "remainingTime": "-5",
            "Uesrsid": "XJwp5I5AXb2GhK04cOVN"
        },
        {
            "date": "2024-05-12",
            "userTeam": "IT전략기획팀",
            "userName": "김가인",
            "department": "사업부서",
            "projectName": "비대면",
            "categoriesName": "회의운영",
            "subcategoriesName": "외부회의",
            "subsubcategoriesName": "회의진행(출장시출장이동시간포함)",
            "baseTime": "2",
            "spentTime": "1.5",
            "status": "완료",
            "note": "[비대면]대전지역암센터VR사용법교육회의",
            "remainingTime": "0.5",
            "Uesrsid": "XJwp5I5AXb2GhK04cOVN"
        },
        {
            "date": "2024-05-12",
            "userTeam": "IT전략기획팀",
            "userName": "김가인",
            "department": "사업부서",
            "projectName": "비대면",
            "categoriesName": "사업부서_검토_수정",
            "subcategoriesName": "상세_검토수정",
            "subsubcategoriesName": "상세_검토수정",
            "baseTime": "3",
            "spentTime": "4",
            "status": "진행중",
            "note": "[비대면]협회물품관리대장작성,암센터물품관리대장회신,사업관련물품정리,주간회의록작성,준비",
            "remainingTime": "-1",
            "Uesrsid": "XJwp5I5AXb2GhK04cOVN"
        },
        {
            "date": "2024-05-14",
            "userTeam": "IT전략기획팀",
            "userName": "김가인",
            "department": "사업부서",
            "projectName": "비대면",
            "categoriesName": "사업부서_검토_수정",
            "subcategoriesName": "상세_검토수정",
            "subsubcategoriesName": "상세_검토수정",
            "baseTime": "3",
            "spentTime": "2",
            "status": "완료",
            "note": "[CRO]제안요청서최종수정회의/공고문수정,검토",
            "remainingTime": "1",
            "Uesrsid": "XJwp5I5AXb2GhK04cOVN"
        },
        {
            "date": "2024-05-14",
            "userTeam": "IT전략기획팀",
            "userName": "김가인",
            "department": "사업부서",
            "projectName": "비대면",
            "categoriesName": "회의운영",
            "subcategoriesName": "외부회의",
            "subsubcategoriesName": "회의진행(출장시출장이동시간포함)",
            "baseTime": "2",
            "spentTime": "0.5",
            "status": "완료",
            "note": "[비대면]실무자주간회의",
            "remainingTime": "1.5",
            "Uesrsid": "XJwp5I5AXb2GhK04cOVN"
        },
        {
            "date": "2024-05-14",
            "userTeam": "IT전략기획팀",
            "userName": "김가인",
            "department": "사업부서",
            "projectName": "비대면",
            "categoriesName": "사업부서_검토_수정",
            "subcategoriesName": "상세_검토수정",
            "subsubcategoriesName": "상세_검토수정",
            "baseTime": "3",
            "spentTime": "2.5",
            "status": "완료",
            "note": "[비대면]협회물품관리대장작성,암센터물품관리대장회신,사업관련물품정리,주간회의록작성,준비",
            "remainingTime": "0.5",
            "Uesrsid": "XJwp5I5AXb2GhK04cOVN"
        },
        {
            "date": "2024-05-16",
            "userTeam": "IT전략기획팀",
            "userName": "김가인",
            "department": "사업부서",
            "projectName": "비대면",
            "categoriesName": "회의운영",
            "subcategoriesName": "내부회의",
            "subsubcategoriesName": "회의진행(사업,협회,기타)",
            "baseTime": "2",
            "spentTime": "2.5",
            "status": "진행중",
            "note": "[비대면]국립암센터문의사항논의",
            "remainingTime": "-0.5",
            "Uesrsid": "XJwp5I5AXb2GhK04cOVN"
        },
        {
            "date": "2024-05-16",
            "userTeam": "IT전략기획팀",
            "userName": "김가인",
            "department": "사업부서",
            "projectName": "비대면",
            "categoriesName": "설문조사",
            "subcategoriesName": "설문조사준비",
            "subsubcategoriesName": "설문조사(교육만족도조사)문항작성",
            "baseTime": "3.5",
            "spentTime": "0.5",
            "status": "진행중",
            "note": "[비대면]VR사업관련건의사항설문지작성논의",
            "remainingTime": "3",
            "Uesrsid": "XJwp5I5AXb2GhK04cOVN"
        },
        {
            "date": "2024-05-16",
            "userTeam": "IT전략기획팀",
            "userName": "김가인",
            "department": "사업부서",
            "projectName": "비대면",
            "categoriesName": "사업부서_검토_수정",
            "subcategoriesName": "간단_검토수정",
            "subsubcategoriesName": "간단_검토수정",
            "baseTime": "1",
            "spentTime": "2",
            "status": "진행중",
            "note": "[비대면]물품관리대장재수집",
            "remainingTime": "-1",
            "Uesrsid": "XJwp5I5AXb2GhK04cOVN"
        },
        {
            "date": "2024-05-17",
            "userTeam": "IT전략기획팀",
            "userName": "김가인",
            "department": "사업부서",
            "projectName": "비대면",
            "categoriesName": "사업부서_검토_수정",
            "subcategoriesName": "간단_검토수정",
            "subsubcategoriesName": "간단_검토수정",
            "baseTime": "1",
            "spentTime": "2",
            "status": "진행중",
            "note": "[비대면]국립암센터문의사항논의",
            "remainingTime": "-1",
            "Uesrsid": "XJwp5I5AXb2GhK04cOVN"
        },
        {
            "date": "2024-05-17",
            "userTeam": "IT전략기획팀",
            "userName": "김가인",
            "department": "사업부서",
            "projectName": "비대면",
            "categoriesName": "회의운영",
            "subcategoriesName": "외부회의",
            "subsubcategoriesName": "회의진행(출장시출장이동시간포함)",
            "baseTime": "2",
            "spentTime": "6.5",
            "status": "완료",
            "note": "[KIDI용역]보험개발원사업건(대한중소병원협회학술세미나홍보)",
            "remainingTime": "-4.5",
            "Uesrsid": "XJwp5I5AXb2GhK04cOVN"
        },
        {
            "date": "2024-05-20",
            "userTeam": "IT전략기획팀",
            "userName": "김가인",
            "department": "사업부서",
            "projectName": "비대면",
            "categoriesName": "행정",
            "subcategoriesName": "문서기안",
            "subsubcategoriesName": "기타",
            "baseTime": "0.2",
            "spentTime": "2",
            "status": "완료",
            "note": "[비대면]수입결의서작성/사업비예산산출내역서작성/지출품의서작성및간단교육",
            "remainingTime": "-1.8",
            "Uesrsid": "XJwp5I5AXb2GhK04cOVN"
        },
        {
            "date": "2024-05-20",
            "userTeam": "IT전략기획팀",
            "userName": "김가인",
            "department": "사업부서",
            "projectName": "비대면",
            "categoriesName": "사업부서_검토_수정",
            "subcategoriesName": "간단_검토수정",
            "subsubcategoriesName": "간단_검토수정",
            "baseTime": "1",
            "spentTime": "4",
            "status": "완료",
            "note": "[비대면]암센터요청자료수집과회신",
            "remainingTime": "-3",
            "Uesrsid": "XJwp5I5AXb2GhK04cOVN"
        },
        {
            "date": "2024-05-21",
            "userTeam": "IT전략기획팀",
            "userName": "김가인",
            "department": "사업부서",
            "projectName": "비대면",
            "categoriesName": "회의운영",
            "subcategoriesName": "내부회의",
            "subsubcategoriesName": "회의진행(사업,협회,기타)",
            "baseTime": "2",
            "spentTime": "1.5",
            "status": "완료",
            "note": "[비대면]개발사항논의",
            "remainingTime": "0.5",
            "Uesrsid": "XJwp5I5AXb2GhK04cOVN"
        },
        {
            "date": "2024-05-21",
            "userTeam": "IT전략기획팀",
            "userName": "김가인",
            "department": "사업부서",
            "projectName": "CRO",
            "categoriesName": "회의운영",
            "subcategoriesName": "내부회의",
            "subsubcategoriesName": "회의진행(사업,협회,기타)",
            "baseTime": "2",
            "spentTime": "1",
            "status": "완료",
            "note": "[CRO]국내기업종사자관련오프라인교육LMS관련회의",
            "remainingTime": "1",
            "Uesrsid": "XJwp5I5AXb2GhK04cOVN"
        },
        {
            "date": "2024-05-21",
            "userTeam": "IT전략기획팀",
            "userName": "김가인",
            "department": "사업부서",
            "projectName": "비대면",
            "categoriesName": "회의운영",
            "subcategoriesName": "외부회의",
            "subsubcategoriesName": "회의진행(출장시출장이동시간포함)",
            "baseTime": "2",
            "spentTime": "5",
            "status": "완료",
            "note": "[비대면]국립암센터대면회의참석5(외부회의)",
            "remainingTime": "-3",
            "Uesrsid": "XJwp5I5AXb2GhK04cOVN"
        },
        {
            "date": "2024-05-22",
            "userTeam": "IT전략기획팀",
            "userName": "김가인",
            "department": "사업부서",
            "projectName": "비대면",
            "categoriesName": "회의운영",
            "subcategoriesName": "내부회의",
            "subsubcategoriesName": "회의진행(사업,협회,기타)",
            "baseTime": "2",
            "spentTime": "2.5",
            "status": "진행중",
            "note": "[비대면]개발및설문조사관련역할분담회의진행",
            "remainingTime": "-0.5",
            "Uesrsid": "XJwp5I5AXb2GhK04cOVN"
        },
        {
            "date": "2024-05-22",
            "userTeam": "IT전략기획팀",
            "userName": "김가인",
            "department": "사업부서",
            "projectName": "비대면",
            "categoriesName": "설문조사",
            "subcategoriesName": "설문조사_배포_수행",
            "subsubcategoriesName": "설문조사배포및참가독려",
            "baseTime": "1",
            "spentTime": "2",
            "status": "완료",
            "note": "[비대면]24년XR플랫폼개선설문조사양식작성및배포",
            "remainingTime": "-1",
            "Uesrsid": "XJwp5I5AXb2GhK04cOVN"
        },
        {
            "date": "2024-05-22",
            "userTeam": "IT전략기획팀",
            "userName": "김가인",
            "department": "사업부서",
            "projectName": "비대면",
            "categoriesName": "사업부서_검토_수정",
            "subcategoriesName": "상세_검토수정",
            "subsubcategoriesName": "상세_검토수정",
            "baseTime": "3",
            "spentTime": "1.5",
            "status": "진행중",
            "note": "[비대면]지역암센터물품관리대장재검토및국내출장검토회의",
            "remainingTime": "1.5",
            "Uesrsid": "XJwp5I5AXb2GhK04cOVN"
        },
        {
            "date": "2024-05-23",
            "userTeam": "IT전략기획팀",
            "userName": "김가인",
            "department": "사업부서",
            "projectName": "비대면",
            "categoriesName": "회의운영",
            "subcategoriesName": "내부회의",
            "subsubcategoriesName": "회의진행(사업,협회,기타)",
            "baseTime": "2",
            "spentTime": "1",
            "status": "진행중",
            "note": "[비대면]VR힐링영상콘텐츠리스트수정관련회의",
            "remainingTime": "1",
            "Uesrsid": "XJwp5I5AXb2GhK04cOVN"
        },
        {
            "date": "2024-05-23",
            "userTeam": "IT전략기획팀",
            "userName": "김가인",
            "department": "사업부서",
            "projectName": "비대면",
            "categoriesName": "행정",
            "subcategoriesName": "경비_지출",
            "subsubcategoriesName": "지출결의",
            "baseTime": "0.2",
            "spentTime": "2",
            "status": "진행중",
            "note": "[비대면]지출결의서작성및간단교육(상계처리)",
            "remainingTime": "-1.8",
            "Uesrsid": "XJwp5I5AXb2GhK04cOVN"
        },
        {
            "date": "2024-05-23",
            "userTeam": "IT전략기획팀",
            "userName": "김가인",
            "department": "사업부서",
            "projectName": "비대면",
            "categoriesName": "설문조사",
            "subcategoriesName": "설문조사_배포_수행",
            "subsubcategoriesName": "설문조사배포및참가독려",
            "baseTime": "1",
            "spentTime": "1",
            "status": "완료",
            "note": "[비대면]전체암센터대상설문조사지재배포및안내",
            "remainingTime": "0",
            "Uesrsid": "XJwp5I5AXb2GhK04cOVN"
        },
        {
            "date": "2024-05-23",
            "userTeam": "IT전략기획팀",
            "userName": "김가인",
            "department": "사업부서",
            "projectName": "비대면",
            "categoriesName": "회의운영",
            "subcategoriesName": "외부회의",
            "subsubcategoriesName": "회의준비(회의실예약,계획수립,회의자료출장결의작성등)",
            "baseTime": "2",
            "spentTime": "1",
            "status": "진행중",
            "note": "[비대면]대전지역암센터VR사용법대면교육일정논의",
            "remainingTime": "1",
            "Uesrsid": "XJwp5I5AXb2GhK04cOVN"
        },
        {
            "date": "2024-05-27",
            "userTeam": "IT전략기획팀",
            "userName": "김가인",
            "department": "사업부서",
            "projectName": "비대면",
            "categoriesName": "사업부서_검토_수정",
            "subcategoriesName": "상세_검토수정",
            "subsubcategoriesName": "상세_검토수정",
            "baseTime": "3",
            "spentTime": "5",
            "status": "진행중",
            "note": "[비대면]국립암센터요청자료회신및비대면주간회의논의자료작성",
            "remainingTime": "-2",
            "Uesrsid": "XJwp5I5AXb2GhK04cOVN"
        },
        {
            "date": "2024-05-27",
            "userTeam": "IT전략기획팀",
            "userName": "김가인",
            "department": "사업부서",
            "projectName": "비대면",
            "categoriesName": "행정",
            "subcategoriesName": "경비_지출",
            "subsubcategoriesName": "지출결의",
            "baseTime": "0.2",
            "spentTime": "1",
            "status": "완료",
            "note": "[비대면]품의작성,지출결의필요자료정리",
            "remainingTime": "-0.8",
            "Uesrsid": "XJwp5I5AXb2GhK04cOVN"
        },
        {
            "date": "2024-05-28",
            "userTeam": "IT전략기획팀",
            "userName": "김가인",
            "department": "사업부서",
            "projectName": "비대면",
            "categoriesName": "사업부서_검토_수정",
            "subcategoriesName": "상세_검토수정",
            "subsubcategoriesName": "상세_검토수정",
            "baseTime": "3",
            "spentTime": "2",
            "status": "진행중",
            "note": "[비대면]지역암센터회신자료수집및작성",
            "remainingTime": "1",
            "Uesrsid": "XJwp5I5AXb2GhK04cOVN"
        },
        {
            "date": "2024-05-28",
            "userTeam": "IT전략기획팀",
            "userName": "김가인",
            "department": "사업부서",
            "projectName": "비대면",
            "categoriesName": "회의운영",
            "subcategoriesName": "외부회의",
            "subsubcategoriesName": "회의진행(출장시출장이동시간포함)",
            "baseTime": "2",
            "spentTime": "1",
            "status": "완료",
            "note": "[비대면]실무자주간회의준비및진행",
            "remainingTime": "1",
            "Uesrsid": "XJwp5I5AXb2GhK04cOVN"
        },
        {
            "date": "2024-05-28",
            "userTeam": "IT전략기획팀",
            "userName": "김가인",
            "department": "사업부서",
            "projectName": "비대면",
            "categoriesName": "회의운영",
            "subcategoriesName": "내부회의",
            "subsubcategoriesName": "회의준비(회의실예약,계획수립,회의자료작성등)",
            "baseTime": "2",
            "spentTime": "3",
            "status": "진행중",
            "note": "[비대면]주간회의에서다룬내용에대한논의",
            "remainingTime": "-1",
            "Uesrsid": "XJwp5I5AXb2GhK04cOVN"
        },
        {
            "date": "2024-05-29",
            "userTeam": "IT전략기획팀",
            "userName": "김가인",
            "department": "사업부서",
            "projectName": "비대면",
            "categoriesName": "행정",
            "subcategoriesName": "회의록_업무추진비",
            "subsubcategoriesName": "회의록작성",
            "baseTime": "1",
            "spentTime": "1",
            "status": "완료",
            "note": "[비대면]내시경세척관련회의록작성",
            "remainingTime": "0",
            "Uesrsid": "XJwp5I5AXb2GhK04cOVN"
        },
        {
            "date": "2024-05-29",
            "userTeam": "IT전략기획팀",
            "userName": "김가인",
            "department": "사업부서",
            "projectName": "비대면",
            "categoriesName": "행정",
            "subcategoriesName": "경비_지출",
            "subsubcategoriesName": "결제건관련증빙서류확인및취합-증빙취합이복잡할경우",
            "baseTime": "1",
            "spentTime": "3",
            "status": "완료",
            "note": "[비대면]전문가활용비/내시경세척관련회의증빙서류취합및지출결의입력",
            "remainingTime": "-2",
            "Uesrsid": "XJwp5I5AXb2GhK04cOVN"
        },
        {
            "date": "2024-05-29",
            "userTeam": "IT전략기획팀",
            "userName": "김가인",
            "department": "사업부서",
            "projectName": "비대면",
            "categoriesName": "행정",
            "subcategoriesName": "경비_지출",
            "subsubcategoriesName": "지출결의",
            "baseTime": "0.2",
            "spentTime": "2",
            "status": "완료",
            "note": "[비대면]복합기및세절기임차료지출결의등록및상계처리에대한간단교육과업로드",
            "remainingTime": "-1.8",
            "Uesrsid": "XJwp5I5AXb2GhK04cOVN"
        },
        {
            "date": "2024-05-30",
            "userTeam": "IT전략기획팀",
            "userName": "김가인",
            "department": "사업부서",
            "projectName": "CRO",
            "categoriesName": "회의운영",
            "subcategoriesName": "내부회의",
            "subsubcategoriesName": "회의진행(사업,협회,기타)",
            "baseTime": "2",
            "spentTime": "2.5",
            "status": "완료",
            "note": "[CRO]내부회의(업체미팅)",
            "remainingTime": "-0.5",
            "Uesrsid": "XJwp5I5AXb2GhK04cOVN"
        },
        {
            "date": "2024-05-30",
            "userTeam": "IT전략기획팀",
            "userName": "김가인",
            "department": "사업부서",
            "projectName": "비대면",
            "categoriesName": "행정",
            "subcategoriesName": "문서기안",
            "subsubcategoriesName": "출장신청서",
            "baseTime": "0.2",
            "spentTime": "2",
            "status": "완료",
            "note": "[비대면]출장예정일정논의,출장신청서작성",
            "remainingTime": "-1.8",
            "Uesrsid": "XJwp5I5AXb2GhK04cOVN"
        },
        {
            "date": "2024-05-31",
            "userTeam": "IT전략기획팀",
            "userName": "김가인",
            "department": "사업부서",
            "projectName": "비대면",
            "categoriesName": "사업부서_검토_수정",
            "subcategoriesName": "상세_검토수정",
            "subsubcategoriesName": "상세_검토수정",
            "baseTime": "3",
            "spentTime": "1",
            "status": "완료",
            "note": "[비대면]국립암센터요청자료작성및회신",
            "remainingTime": "2",
            "Uesrsid": "XJwp5I5AXb2GhK04cOVN"
        },
        {
            "date": "2024-05-31",
            "userTeam": "IT전략기획팀",
            "userName": "김가인",
            "department": "사업부서",
            "projectName": "CRO",
            "categoriesName": "회의운영",
            "subcategoriesName": "외부회의",
            "subsubcategoriesName": "회의진행(출장시출장이동시간포함)",
            "baseTime": "2",
            "spentTime": "5",
            "status": "완료",
            "note": "[CRO]국내기업종사자에대한의료기기임상시험에대한기본교육참석",
            "remainingTime": "-3",
            "Uesrsid": "XJwp5I5AXb2GhK04cOVN"
        },
        {
            "date": "2024-06-03",
            "userTeam": "IT전략기획팀",
            "userName": "김가인",
            "department": "사업부서",
            "projectName": "비대면",
            "categoriesName": "회의운영",
            "subcategoriesName": "외부회의",
            "subsubcategoriesName": "회의진행(출장시출장이동시간포함)",
            "baseTime": "2",
            "spentTime": "6",
            "status": "완료",
            "note": "[비대면]VR오큘러스사용현황체크및교육을위한대전지역암센터방문",
            "remainingTime": "-4",
            "Uesrsid": "XJwp5I5AXb2GhK04cOVN"
        },
        {
            "date": "2024-06-04",
            "userTeam": "IT전략기획팀",
            "userName": "김가인",
            "department": "사업부서",
            "projectName": "비대면",
            "categoriesName": "사업부서_검토_수정",
            "subcategoriesName": "간단_검토수정",
            "subsubcategoriesName": "간단_검토수정",
            "baseTime": "1",
            "spentTime": "3",
            "status": "진행중",
            "note": "[비대면]국립암센터요청자료검토및회신",
            "remainingTime": "-2",
            "Uesrsid": "XJwp5I5AXb2GhK04cOVN"
        },
        {
            "date": "2024-06-04",
            "userTeam": "IT전략기획팀",
            "userName": "김가인",
            "department": "사업부서",
            "projectName": "비대면",
            "categoriesName": "회의운영",
            "subcategoriesName": "내부회의",
            "subsubcategoriesName": "회의진행(사업,협회,기타)",
            "baseTime": "2",
            "spentTime": "2",
            "status": "완료",
            "note": "[비대면]지역암센터6월중방문일정논의및협의",
            "remainingTime": "0",
            "Uesrsid": "XJwp5I5AXb2GhK04cOVN"
        },
        {
            "date": "2024-06-05",
            "userTeam": "IT전략기획팀",
            "userName": "김가인",
            "department": "사업부서",
            "projectName": "비대면",
            "categoriesName": "사업부서_검토_수정",
            "subcategoriesName": "간단_검토수정",
            "subsubcategoriesName": "간단_검토수정",
            "baseTime": "1",
            "spentTime": "2",
            "status": "완료",
            "note": "[비대면]국립암센터요청자료회신",
            "remainingTime": "-1",
            "Uesrsid": "XJwp5I5AXb2GhK04cOVN"
        },
        {
            "date": "2024-06-05",
            "userTeam": "IT전략기획팀",
            "userName": "김가인",
            "department": "사업부서",
            "projectName": "비대면",
            "categoriesName": "회의운영",
            "subcategoriesName": "외부회의",
            "subsubcategoriesName": "회의진행(출장시출장이동시간포함)",
            "baseTime": "2",
            "spentTime": "3",
            "status": "완료",
            "note": "[비대면]국립암센터대면회의참석(국립암센터방문)",
            "remainingTime": "-1",
            "Uesrsid": "XJwp5I5AXb2GhK04cOVN"
        },
        {
            "date": "2024-06-07",
            "userTeam": "IT전략기획팀",
            "userName": "김가인",
            "department": "사업부서",
            "projectName": "비대면",
            "categoriesName": "사업부서_검토_수정",
            "subcategoriesName": "간단_검토수정",
            "subsubcategoriesName": "간단_검토수정",
            "baseTime": "1",
            "spentTime": "6",
            "status": "완료",
            "note": "[비대면]주간업무정리및지출결의증빙서류준비",
            "remainingTime": "-5",
            "Uesrsid": "XJwp5I5AXb2GhK04cOVN"
        },
        {
            "date": "2024-06-10",
            "userTeam": "IT전략기획팀",
            "userName": "김가인",
            "department": "사업부서",
            "projectName": "비대면",
            "categoriesName": "사업부서_검토_수정",
            "subcategoriesName": "상세_검토수정",
            "subsubcategoriesName": "상세_검토수정",
            "baseTime": "3",
            "spentTime": "5",
            "status": "진행중",
            "note": "[비대면]국립암센터요청자료수정건진행",
            "remainingTime": "-2",
            "Uesrsid": "XJwp5I5AXb2GhK04cOVN"
        },
        {
            "date": "2024-06-11",
            "userTeam": "IT전략기획팀",
            "userName": "김가인",
            "department": "사업부서",
            "projectName": "비대면",
            "categoriesName": "회의운영",
            "subcategoriesName": "외부회의",
            "subsubcategoriesName": "회의진행(출장시출장이동시간포함)",
            "baseTime": "2",
            "spentTime": "1",
            "status": "완료",
            "note": "[비대면]국립암센터실무자주간회의",
            "remainingTime": "1",
            "Uesrsid": "XJwp5I5AXb2GhK04cOVN"
        },
        {
            "date": "2024-06-11",
            "userTeam": "IT전략기획팀",
            "userName": "김가인",
            "department": "사업부서",
            "projectName": "비대면",
            "categoriesName": "회의운영",
            "subcategoriesName": "내부회의",
            "subsubcategoriesName": "회의진행(사업,협회,기타)",
            "baseTime": "2",
            "spentTime": "1",
            "status": "완료",
            "note": "[비대면]국립암센터다학제시연을위한리허설회의",
            "remainingTime": "1",
            "Uesrsid": "XJwp5I5AXb2GhK04cOVN"
        },
        {
            "date": "2024-06-11",
            "userTeam": "IT전략기획팀",
            "userName": "김가인",
            "department": "사업부서",
            "projectName": "비대면",
            "categoriesName": "회의운영",
            "subcategoriesName": "내부회의",
            "subsubcategoriesName": "회의자료작성(PPT)",
            "baseTime": "3",
            "spentTime": "1",
            "status": "완료",
            "note": "[비대면]국립암센터다학제시연을위한ppt제작",
            "remainingTime": "2",
            "Uesrsid": "XJwp5I5AXb2GhK04cOVN"
        },
        {
            "date": "2024-06-11",
            "userTeam": "IT전략기획팀",
            "userName": "김가인",
            "department": "사업부서",
            "projectName": "비대면",
            "categoriesName": "사업부서_검토_수정",
            "subcategoriesName": "상세_검토수정",
            "subsubcategoriesName": "상세_검토수정",
            "baseTime": "3",
            "spentTime": "3",
            "status": "진행중",
            "note": "[비대면]아바소송대응지원회의및암센터요청업무수행",
            "remainingTime": "0",
            "Uesrsid": "XJwp5I5AXb2GhK04cOVN"
        },
        {
            "date": "2024-06-12",
            "userTeam": "IT전략기획팀",
            "userName": "김가인",
            "department": "사업부서",
            "projectName": "비대면",
            "categoriesName": "회의운영",
            "subcategoriesName": "내부회의",
            "subsubcategoriesName": "회의진행(사업,협회,기타)",
            "baseTime": "2",
            "spentTime": "2",
            "status": "진행중",
            "note": "[비대면]아바소송대응지원회의및암센터요청업무수행",
            "remainingTime": "0",
            "Uesrsid": "XJwp5I5AXb2GhK04cOVN"
        },
        {
            "date": "2024-06-13",
            "userTeam": "IT전략기획팀",
            "userName": "김가인",
            "department": "사업부서",
            "projectName": "비대면",
            "categoriesName": "회의운영",
            "subcategoriesName": "내부회의",
            "subsubcategoriesName": "회의진행(사업,협회,기타)",
            "baseTime": "2",
            "spentTime": "2",
            "status": "진행중",
            "note": "[비대면]아바소송대응지원회의및암센터요청업무수행",
            "remainingTime": "0",
            "Uesrsid": "XJwp5I5AXb2GhK04cOVN"
        },
        {
            "date": "2024-06-14",
            "userTeam": "IT전략기획팀",
            "userName": "김가인",
            "department": "사업부서",
            "projectName": "비대면",
            "categoriesName": "회의운영",
            "subcategoriesName": "내부회의",
            "subsubcategoriesName": "회의진행(사업,협회,기타)",
            "baseTime": "2",
            "spentTime": "2",
            "status": "완료",
            "note": "물품관리목록대장업무를위한내부논의후문서수정",
            "remainingTime": "0",
            "Uesrsid": "XJwp5I5AXb2GhK04cOVN"
        },
        {
            "date": "2024-06-14",
            "userTeam": "IT전략기획팀",
            "userName": "김가인",
            "department": "사업부서",
            "projectName": "비대면",
            "categoriesName": "사업부서_기타",
            "subcategoriesName": "협회기타",
            "subsubcategoriesName": "협회기타(자리이동,청소,주간회의등)",
            "baseTime": "1",
            "spentTime": "0.5",
            "status": "완료",
            "note": "패밀리데이사무실청소",
            "remainingTime": "0.5",
            "Uesrsid": "XJwp5I5AXb2GhK04cOVN"
        },
        {
            "date": "2024-07-08",
            "userTeam": "통합헬스케어기획팀",
            "userName": "김가인",
            "department": "사업부서",
            "projectName": "비대면",
            "categoriesName": "사업부서_기타",
            "subcategoriesName": "타부서지원",
            "subsubcategoriesName": "타부서지원",
            "baseTime": "1",
            "spentTime": "6",
            "status": "진행중",
            "note": "비대면사업인수인계를위한파일정리및인수인계서작성",
            "remainingTime": "-5",
            "Uesrsid": "XJwp5I5AXb2GhK04cOVN"
        },
        {
            "date": "2024-07-09",
            "userTeam": "통합헬스케어기획팀",
            "userName": "김가인",
            "department": "사업부서",
            "projectName": "비대면",
            "categoriesName": "사업부서_기타",
            "subcategoriesName": "타부서지원",
            "subsubcategoriesName": "타부서지원",
            "baseTime": "1",
            "spentTime": "2",
            "status": "진행중",
            "note": "[비대면]인수인계서작성",
            "remainingTime": "-1",
            "Uesrsid": "XJwp5I5AXb2GhK04cOVN"
        },
        {
            "date": "2024-07-09",
            "userTeam": "통합헬스케어기획팀",
            "userName": "김가인",
            "department": "사업부서",
            "projectName": "비대면",
            "categoriesName": "사업부서_기타",
            "subcategoriesName": "타부서지원",
            "subsubcategoriesName": "타부서지원",
            "baseTime": "1",
            "spentTime": "4",
            "status": "완료",
            "note": "[비대면]용역업체착수보고회및주간회의(국립암센터출장)",
            "remainingTime": "-3",
            "Uesrsid": "XJwp5I5AXb2GhK04cOVN"
        },
        {
            "date": "2024-07-10",
            "userTeam": "통합헬스케어기획팀",
            "userName": "김가인",
            "department": "사업부서",
            "projectName": "비대면",
            "categoriesName": "사업부서_기타",
            "subcategoriesName": "타부서지원",
            "subsubcategoriesName": "타부서지원",
            "baseTime": "1",
            "spentTime": "2",
            "status": "완료",
            "note": "[비대면]인수인계회의진행",
            "remainingTime": "-1",
            "Uesrsid": "XJwp5I5AXb2GhK04cOVN"
        },
        {
            "date": "2024-07-10",
            "userTeam": "통합헬스케어기획팀",
            "userName": "김가인",
            "department": "사업부서",
            "projectName": "비대면",
            "categoriesName": "사업부서_기타",
            "subcategoriesName": "타부서지원",
            "subsubcategoriesName": "타부서지원",
            "baseTime": "1",
            "spentTime": "4",
            "status": "진행중",
            "note": "[비대면]지출결의를위한문서준비및부산지역암센터출장준비등행정업무다수",
            "remainingTime": "-3",
            "Uesrsid": "XJwp5I5AXb2GhK04cOVN"
        },
        {
            "date": "2024-07-11",
            "userTeam": "통합헬스케어기획팀",
            "userName": "김가인",
            "department": "사업부서",
            "projectName": "비대면",
            "categoriesName": "사업부서_기타",
            "subcategoriesName": "타부서지원",
            "subsubcategoriesName": "타부서지원",
            "baseTime": "1",
            "spentTime": "5",
            "status": "완료",
            "note": "[비대면]복지부요청제출파일작성및인수인계서작성",
            "remainingTime": "-4",
            "Uesrsid": "XJwp5I5AXb2GhK04cOVN"
        },
        {
            "date": "2024-07-12",
            "userTeam": "통합헬스케어기획팀",
            "userName": "김가인",
            "department": "사업부서",
            "projectName": "비대면",
            "categoriesName": "사업부서_기타",
            "subcategoriesName": "타부서지원",
            "subsubcategoriesName": "타부서지원",
            "baseTime": "1",
            "spentTime": "6",
            "status": "완료",
            "note": "[비대면]부산지역암센터VR관련회의출장",
            "remainingTime": "-5",
            "Uesrsid": "XJwp5I5AXb2GhK04cOVN"
        },
        {
            "date": "2024-07-15",
            "userTeam": "통합헬스케어기획팀",
            "userName": "김가인",
            "department": "사업부서",
            "projectName": "비대면",
            "categoriesName": "사업부서_기타",
            "subcategoriesName": "타부서지원",
            "subsubcategoriesName": "타부서지원",
            "baseTime": "1",
            "spentTime": "6",
            "status": "완료",
            "note": "[비대면]복지부요청문서법률검토메일작성및인수인계,제출파일작성",
            "remainingTime": "-5",
            "Uesrsid": "XJwp5I5AXb2GhK04cOVN"
        },
        {
            "date": "2024-07-16",
            "userTeam": "통합헬스케어기획팀",
            "userName": "김가인",
            "department": "사업부서",
            "projectName": "비대면",
            "categoriesName": "사업부서_기타",
            "subcategoriesName": "타부서지원",
            "subsubcategoriesName": "타부서지원",
            "baseTime": "1",
            "spentTime": "1",
            "status": "완료",
            "note": "[비대면]실무자주간회의참석",
            "remainingTime": "0",
            "Uesrsid": "XJwp5I5AXb2GhK04cOVN"
        },
        {
            "date": "2024-07-16",
            "userTeam": "통합헬스케어기획팀",
            "userName": "김가인",
            "department": "사업부서",
            "projectName": "비대면",
            "categoriesName": "사업부서_기타",
            "subcategoriesName": "타부서지원",
            "subsubcategoriesName": "타부서지원",
            "baseTime": "1",
            "spentTime": "4",
            "status": "완료",
            "note": "[비대면]주간보고서작성방법및기타인수인계진행",
            "remainingTime": "-3",
            "Uesrsid": "XJwp5I5AXb2GhK04cOVN"
        },
        {
            "date": "2024-07-17",
            "userTeam": "통합헬스케어기획팀",
            "userName": "김가인",
            "department": "사업부서",
            "projectName": "비대면",
            "categoriesName": "사업부서_기타",
            "subcategoriesName": "타부서지원",
            "subsubcategoriesName": "타부서지원",
            "baseTime": "1",
            "spentTime": "1",
            "status": "완료",
            "note": "[비대면]암케어디지털통합플랫폼WBS인수및리뷰",
            "remainingTime": "0",
            "Uesrsid": "XJwp5I5AXb2GhK04cOVN"
        },
        {
            "date": "2024-07-17",
            "userTeam": "통합헬스케어기획팀",
            "userName": "김가인",
            "department": "사업부서",
            "projectName": "비대면",
            "categoriesName": "사업부서_기타",
            "subcategoriesName": "타부서지원",
            "subsubcategoriesName": "타부서지원",
            "baseTime": "1",
            "spentTime": "4",
            "status": "완료",
            "note": "[비대면]국립암센터요청장루케어,내시경세척관련수정요청사항소통및업무지원",
            "remainingTime": "-3",
            "Uesrsid": "XJwp5I5AXb2GhK04cOVN"
        },
        {
            "date": "2024-07-18",
            "userTeam": "통합헬스케어기획팀",
            "userName": "김가인",
            "department": "사업부서",
            "projectName": "비대면",
            "categoriesName": "사업부서_기타",
            "subcategoriesName": "타부서지원",
            "subsubcategoriesName": "타부서지원",
            "baseTime": "1",
            "spentTime": "5",
            "status": "진행중",
            "note": "[비대면]7월지출결의회의및출장자료취합",
            "remainingTime": "-4",
            "Uesrsid": "XJwp5I5AXb2GhK04cOVN"
        },
        {
            "date": "2024-07-22",
            "userTeam": "통합헬스케어기획팀",
            "userName": "김가인",
            "department": "사업부서",
            "projectName": "비대면",
            "categoriesName": "사업부서_기타",
            "subcategoriesName": "타부서지원",
            "subsubcategoriesName": "타부서지원",
            "baseTime": "1",
            "spentTime": "4",
            "status": "완료",
            "note": "[비대면]출장보고서작성및지출결의작성",
            "remainingTime": "-3",
            "Uesrsid": "XJwp5I5AXb2GhK04cOVN"
        },
        {
            "date": "2024-07-26",
            "userTeam": "통합헬스케어기획팀",
            "userName": "김가인",
            "department": "사업부서",
            "projectName": "한림원용역",
            "categoriesName": "사업부서_검토_수정",
            "subcategoriesName": "간단_검토수정",
            "subsubcategoriesName": "간단_검토수정",
            "baseTime": "1",
            "spentTime": "4",
            "status": "완료",
            "note": "사업관련기업지원범위체크및시내출장준비",
            "remainingTime": "-3",
            "Uesrsid": "XJwp5I5AXb2GhK04cOVN"
        },
        {
            "date": "2024-07-26",
            "userTeam": "통합헬스케어기획팀",
            "userName": "김가인",
            "department": "사업부서",
            "projectName": "한림원용역",
            "categoriesName": "회의운영",
            "subcategoriesName": "외부회의",
            "subsubcategoriesName": "회의진행(출장시출장이동시간포함)",
            "baseTime": "2",
            "spentTime": "4",
            "status": "완료",
            "note": "로엔서지컬기업지원범위문의관련회의",
            "remainingTime": "-2",
            "Uesrsid": "XJwp5I5AXb2GhK04cOVN"
        },
        {
            "date": "2024-07-29",
            "userTeam": "통합헬스케어기획팀",
            "userName": "김가인",
            "department": "사업부서",
            "projectName": "비대면",
            "categoriesName": "사업부서_기타",
            "subcategoriesName": "타부서지원",
            "subsubcategoriesName": "타부서지원",
            "baseTime": "1",
            "spentTime": "6",
            "status": "완료",
            "note": "[비대면]7월출장보고작성및기안,회의록작성",
            "remainingTime": "-5",
            "Uesrsid": "XJwp5I5AXb2GhK04cOVN"
        },
        {
            "date": "2024-07-30",
            "userTeam": "통합헬스케어기획팀",
            "userName": "김가인",
            "department": "사업부서",
            "projectName": "비대면",
            "categoriesName": "사업부서_기타",
            "subcategoriesName": "타부서지원",
            "subsubcategoriesName": "타부서지원",
            "baseTime": "1",
            "spentTime": "6",
            "status": "완료",
            "note": "[비대면]출장보고후지출결의서입력",
            "remainingTime": "-5",
            "Uesrsid": "XJwp5I5AXb2GhK04cOVN"
        },
        {
            "date": "2024-07-31",
            "userTeam": "통합헬스케어기획팀",
            "userName": "김가인",
            "department": "사업부서",
            "projectName": "한림원용역",
            "categoriesName": "사업부서_검토_수정",
            "subcategoriesName": "간단_검토수정",
            "subsubcategoriesName": "간단_검토수정",
            "baseTime": "1",
            "spentTime": "6",
            "status": "완료",
            "note": "해외진출지원컨설팅참가기업선정평가준비및진행",
            "remainingTime": "-5",
            "Uesrsid": "XJwp5I5AXb2GhK04cOVN"
        },
        {
            "date": "2024-08-01",
            "userTeam": "통합헬스케어기획팀",
            "userName": "김가인",
            "department": "사업부서",
            "projectName": "한림원용역",
            "categoriesName": "회의운영",
            "subcategoriesName": "외부회의",
            "subsubcategoriesName": "회의진행(출장시출장이동시간포함)",
            "baseTime": "2",
            "spentTime": "4",
            "status": "완료",
            "note": "한-베디지털포럼관련전담기관(NIPA)회의",
            "remainingTime": "-2",
            "Uesrsid": "XJwp5I5AXb2GhK04cOVN"
        },
        {
            "date": "2024-08-02",
            "userTeam": "통합헬스케어기획팀",
            "userName": "김가인",
            "department": "사업부서",
            "projectName": "SWMD",
            "categoriesName": "전시회",
            "subcategoriesName": "전시회준비",
            "subsubcategoriesName": "전시회참가물품확인(족자봉,브로슈어,홍보물,신문등)",
            "baseTime": "1",
            "spentTime": "3",
            "status": "진행중",
            "note": "RSNA2024등록",
            "remainingTime": "-2",
            "Uesrsid": "XJwp5I5AXb2GhK04cOVN"
        },
        {
            "date": "2024-08-07",
            "userTeam": "통합헬스케어기획팀",
            "userName": "김가인",
            "department": "사업부서",
            "projectName": "SWMD",
            "categoriesName": "사업부서_기타",
            "subcategoriesName": "협회기타",
            "subsubcategoriesName": "협회기타(자리이동,청소,주간회의등)",
            "baseTime": "1",
            "spentTime": "3",
            "status": "진행중",
            "note": "사업점검관리및관리시트작성",
            "remainingTime": "-2",
            "Uesrsid": "XJwp5I5AXb2GhK04cOVN"
        },
        {
            "date": "2024-08-08",
            "userTeam": "통합헬스케어기획팀",
            "userName": "김가인",
            "department": "사업부서",
            "projectName": "한림원용역",
            "categoriesName": "사업부서_검토_수정",
            "subcategoriesName": "상세_검토수정",
            "subsubcategoriesName": "상세_검토수정",
            "baseTime": "3",
            "spentTime": "4",
            "status": "진행중",
            "note": "사업인수인계및업무파악",
            "remainingTime": "-1",
            "Uesrsid": "XJwp5I5AXb2GhK04cOVN"
        },
        {
            "date": "2024-08-09",
            "userTeam": "통합헬스케어기획팀",
            "userName": "김가인",
            "department": "사업부서",
            "projectName": "한림원용역",
            "categoriesName": "사업부서_검토_수정",
            "subcategoriesName": "상세_검토수정",
            "subsubcategoriesName": "상세_검토수정",
            "baseTime": "3",
            "spentTime": "4",
            "status": "진행중",
            "note": "사업인수인계및업무파악",
            "remainingTime": "-1",
            "Uesrsid": "XJwp5I5AXb2GhK04cOVN"
        },
        {
            "date": "2024-08-12",
            "userTeam": "통합헬스케어기획팀",
            "userName": "김가인",
            "department": "사업부서",
            "projectName": "한림원용역",
            "categoriesName": "사업부서_기타",
            "subcategoriesName": "협회기타",
            "subsubcategoriesName": "협회기타(자리이동,청소,주간회의등)",
            "baseTime": "1",
            "spentTime": "3",
            "status": "진행중",
            "note": "사업점검관리및관리시트작성",
            "remainingTime": "-2",
            "Uesrsid": "XJwp5I5AXb2GhK04cOVN"
        },
        {
            "date": "2024-08-13",
            "userTeam": "통합헬스케어기획팀",
            "userName": "김가인",
            "department": "사업부서",
            "projectName": "SWMD",
            "categoriesName": "회의운영",
            "subcategoriesName": "외부회의",
            "subsubcategoriesName": "회의진행(출장시출장이동시간포함)",
            "baseTime": "2",
            "spentTime": "6",
            "status": "완료",
            "note": "교육관련강의사전기획",
            "remainingTime": "-4",
            "Uesrsid": "XJwp5I5AXb2GhK04cOVN"
        },
        {
            "date": "2024-08-14",
            "userTeam": "통합헬스케어기획팀",
            "userName": "김가인",
            "department": "사업부서",
            "projectName": "기타",
            "categoriesName": "사업부서_기타",
            "subcategoriesName": "협회기타",
            "subsubcategoriesName": "협회기타(자리이동,청소,주간회의등)",
            "baseTime": "1",
            "spentTime": "4",
            "status": "진행중",
            "note": "사업점검관리및관리시트작성",
            "remainingTime": "-3",
            "Uesrsid": "XJwp5I5AXb2GhK04cOVN"
        },
        {
            "date": "2024-08-19",
            "userTeam": "통합헬스케어기획팀",
            "userName": "김가인",
            "department": "사업부서",
            "projectName": "SWMD",
            "categoriesName": "사업부서_기타",
            "subcategoriesName": "협회기타",
            "subsubcategoriesName": "협회기타(자리이동,청소,주간회의등)",
            "baseTime": "1",
            "spentTime": "8",
            "status": "완료",
            "note": "GMP교육",
            "remainingTime": "-7",
            "Uesrsid": "XJwp5I5AXb2GhK04cOVN"
        },
        {
            "date": "2024-08-20",
            "userTeam": "통합헬스케어기획팀",
            "userName": "김가인",
            "department": "사업부서",
            "projectName": "SWMD",
            "categoriesName": "사업부서_기타",
            "subcategoriesName": "협회기타",
            "subsubcategoriesName": "협회기타(자리이동,청소,주간회의등)",
            "baseTime": "1",
            "spentTime": "8",
            "status": "완료",
            "note": "GMP교육",
            "remainingTime": "-7",
            "Uesrsid": "XJwp5I5AXb2GhK04cOVN"
        },
        {
            "date": "2024-08-21",
            "userTeam": "통합헬스케어기획팀",
            "userName": "김가인",
            "department": "사업부서",
            "projectName": "SWMD",
            "categoriesName": "사업부서_기타",
            "subcategoriesName": "협회기타",
            "subsubcategoriesName": "협회기타(자리이동,청소,주간회의등)",
            "baseTime": "1",
            "spentTime": "8",
            "status": "완료",
            "note": "GMP교육",
            "remainingTime": "-7",
            "Uesrsid": "XJwp5I5AXb2GhK04cOVN"
        },
        {
            "date": "2024-08-22",
            "userTeam": "통합헬스케어기획팀",
            "userName": "김가인",
            "department": "사업부서",
            "projectName": "SWMD",
            "categoriesName": "사업부서_검토_수정",
            "subcategoriesName": "상세_검토수정",
            "subsubcategoriesName": "상세_검토수정",
            "baseTime": "3",
            "spentTime": "4",
            "status": "진행중",
            "note": "사업인수인계및업무파악,교육",
            "remainingTime": "-1",
            "Uesrsid": "XJwp5I5AXb2GhK04cOVN"
        },
        {
            "date": "2024-08-23",
            "userTeam": "통합헬스케어기획팀",
            "userName": "김가인",
            "department": "사업부서",
            "projectName": "한림원용역",
            "categoriesName": "사업부서_검토_수정",
            "subcategoriesName": "상세_검토수정",
            "subsubcategoriesName": "상세_검토수정",
            "baseTime": "3",
            "spentTime": "4",
            "status": "진행중",
            "note": "사업인수인계및업무파악,교육",
            "remainingTime": "-1",
            "Uesrsid": "XJwp5I5AXb2GhK04cOVN"
        },
        {
            "date": "2024-08-27",
            "userTeam": "통합헬스케어기획팀",
            "userName": "김가인",
            "department": "사업부서",
            "projectName": "SWMD",
            "categoriesName": "사업부서_검토_수정",
            "subcategoriesName": "상세_검토수정",
            "subsubcategoriesName": "상세_검토수정",
            "baseTime": "3",
            "spentTime": "4",
            "status": "진행중",
            "note": "사업인수인계및업무파악,교육",
            "remainingTime": "-1",
            "Uesrsid": "XJwp5I5AXb2GhK04cOVN"
        },
        {
            "date": "2024-08-28",
            "userTeam": "통합헬스케어기획팀",
            "userName": "김가인",
            "department": "사업부서",
            "projectName": "한림원용역",
            "categoriesName": "사업부서_검토_수정",
            "subcategoriesName": "상세_검토수정",
            "subsubcategoriesName": "상세_검토수정",
            "baseTime": "3",
            "spentTime": "4",
            "status": "진행중",
            "note": "사업인수인계및업무파악,교육",
            "remainingTime": "-1",
            "Uesrsid": "XJwp5I5AXb2GhK04cOVN"
        },
        {
            "date": "2024-08-29",
            "userTeam": "통합헬스케어기획팀",
            "userName": "김가인",
            "department": "사업부서",
            "projectName": "SWMD",
            "categoriesName": "사업부서_검토_수정",
            "subcategoriesName": "상세_검토수정",
            "subsubcategoriesName": "상세_검토수정",
            "baseTime": "3",
            "spentTime": "4",
            "status": "진행중",
            "note": "사업인수인계및업무파악,교육",
            "remainingTime": "-1",
            "Uesrsid": "XJwp5I5AXb2GhK04cOVN"
        },
        {
            "date": "2024-08-30",
            "userTeam": "통합헬스케어기획팀",
            "userName": "김가인",
            "department": "사업부서",
            "projectName": "한림원용역",
            "categoriesName": "사업부서_검토_수정",
            "subcategoriesName": "상세_검토수정",
            "subsubcategoriesName": "상세_검토수정",
            "baseTime": "3",
            "spentTime": "4",
            "status": "완료",
            "note": "사업인수인계및업무파악,교육",
            "remainingTime": "-1",
            "Uesrsid": "XJwp5I5AXb2GhK04cOVN"
        },
        {
            "date": "2024-09-02",
            "userTeam": "통합헬스케어기획팀",
            "userName": "김가인",
            "department": "사업부서",
            "projectName": "SWMD",
            "categoriesName": "사업부서_검토_수정",
            "subcategoriesName": "상세_검토수정",
            "subsubcategoriesName": "상세_검토수정",
            "baseTime": "3",
            "spentTime": "4",
            "status": "완료",
            "note": "사업인수인계및업무파악,교육",
            "remainingTime": "-1",
            "Uesrsid": "XJwp5I5AXb2GhK04cOVN"
        },
        {
            "date": "2024-09-03",
            "userTeam": "통합헬스케어기획팀",
            "userName": "김가인",
            "department": "사업부서",
            "projectName": "SWMD",
            "categoriesName": "사업부서_기타",
            "subcategoriesName": "협회기타",
            "subsubcategoriesName": "협회기타(자리이동,청소,주간회의등)",
            "baseTime": "1",
            "spentTime": "8",
            "status": "완료",
            "note": "GMP심사원교육",
            "remainingTime": "-7",
            "Uesrsid": "XJwp5I5AXb2GhK04cOVN"
        },
        {
            "date": "2024-09-04",
            "userTeam": "통합헬스케어기획팀",
            "userName": "김가인",
            "department": "사업부서",
            "projectName": "SWMD",
            "categoriesName": "사업부서_기타",
            "subcategoriesName": "협회기타",
            "subsubcategoriesName": "협회기타(자리이동,청소,주간회의등)",
            "baseTime": "1",
            "spentTime": "8",
            "status": "완료",
            "note": "GMP심사원교육",
            "remainingTime": "-7",
            "Uesrsid": "XJwp5I5AXb2GhK04cOVN"
        },
        {
            "date": "2024-09-05",
            "userTeam": "통합헬스케어기획팀",
            "userName": "김가인",
            "department": "사업부서",
            "projectName": "SWMD",
            "categoriesName": "사업부서_기타",
            "subcategoriesName": "협회기타",
            "subsubcategoriesName": "협회기타(자리이동,청소,주간회의등)",
            "baseTime": "1",
            "spentTime": "5",
            "status": "완료",
            "note": "환자중심의료제품안전관리정책토론회참석",
            "remainingTime": "-4",
            "Uesrsid": "XJwp5I5AXb2GhK04cOVN"
        },
        {
            "date": "2024-09-06",
            "userTeam": "통합헬스케어기획팀",
            "userName": "김가인",
            "department": "사업부서",
            "projectName": "SWMD",
            "categoriesName": "컨설팅_교육_조사분석",
            "subcategoriesName": "컨설팅_교육_조사분석_수행",
            "subsubcategoriesName": "사업관련조사분석자료분석준비",
            "baseTime": "4",
            "spentTime": "4",
            "status": "완료",
            "note": "법률서비스관련단가조사",
            "remainingTime": "0",
            "Uesrsid": "XJwp5I5AXb2GhK04cOVN"
        },
        {
            "date": "2024-09-09",
            "userTeam": "통합헬스케어기획팀",
            "userName": "김가인",
            "department": "사업부서",
            "projectName": "한림원용역",
            "categoriesName": "회의운영",
            "subcategoriesName": "외부회의",
            "subsubcategoriesName": "회의진행(출장시출장이동시간포함)",
            "baseTime": "2",
            "spentTime": "5",
            "status": "완료",
            "note": "한-베디지털전환포럼'NIPA회의",
            "remainingTime": "-3",
            "Uesrsid": "XJwp5I5AXb2GhK04cOVN"
        },
        {
            "date": "2024-09-10",
            "userTeam": "통합헬스케어기획팀",
            "userName": "김가인",
            "department": "사업부서",
            "projectName": "한림원용역",
            "categoriesName": "전시회",
            "subcategoriesName": "전시회준비",
            "subsubcategoriesName": "참가계획수립",
            "baseTime": "5",
            "spentTime": "3",
            "status": "완료",
            "note": "한-베디지털전환포럼'계획수립",
            "remainingTime": "2",
            "Uesrsid": "XJwp5I5AXb2GhK04cOVN"
        },
        {
            "date": "2024-09-11",
            "userTeam": "통합헬스케어기획팀",
            "userName": "김가인",
            "department": "사업부서",
            "projectName": "기타",
            "categoriesName": "사업부서_검토_수정",
            "subcategoriesName": "상세_검토수정",
            "subsubcategoriesName": "상세_검토수정",
            "baseTime": "3",
            "spentTime": "4",
            "status": "진행중",
            "note": "산업부신규사업(AI슬립테크)기획서관련자료조사",
            "remainingTime": "-1",
            "Uesrsid": "XJwp5I5AXb2GhK04cOVN"
        },
        {
            "date": "2024-09-12",
            "userTeam": "통합헬스케어기획팀",
            "userName": "김가인",
            "department": "사업부서",
            "projectName": "한림원용역",
            "categoriesName": "회의운영",
            "subcategoriesName": "외부회의",
            "subsubcategoriesName": "회의진행(출장시출장이동시간포함)",
            "baseTime": "2",
            "spentTime": "5",
            "status": "완료",
            "note": "NIPA-한국의료기기협동조합베트남현지의료기기지원센터간간담회추진회의",
            "remainingTime": "-3",
            "Uesrsid": "XJwp5I5AXb2GhK04cOVN"
        },
        {
            "date": "2024-09-13",
            "userTeam": "통합헬스케어기획팀",
            "userName": "김가인",
            "department": "사업부서",
            "projectName": "SWMD",
            "categoriesName": "회의운영",
            "subcategoriesName": "외부회의",
            "subsubcategoriesName": "회의진행(출장시출장이동시간포함)",
            "baseTime": "2",
            "spentTime": "5",
            "status": "완료",
            "note": "소프트웨어의료기기등인허가지원사업'중간보고회자료준비",
            "remainingTime": "-3",
            "Uesrsid": "XJwp5I5AXb2GhK04cOVN"
        },
        {
            "date": "2024-09-24",
            "userTeam": "통합헬스케어기획팀",
            "userName": "김가인",
            "department": "사업부서",
            "projectName": "SWMD",
            "categoriesName": "회의운영",
            "subcategoriesName": "외부회의",
            "subsubcategoriesName": "회의진행(출장시출장이동시간포함)",
            "baseTime": "2",
            "spentTime": "5",
            "status": "완료",
            "note": "소프트웨어의료기기등인허가지원사업'중간보고회",
            "remainingTime": "-3",
            "Uesrsid": "XJwp5I5AXb2GhK04cOVN"
        },
        {
            "date": "2024-09-25",
            "userTeam": "통합헬스케어기획팀",
            "userName": "김가인",
            "department": "사업부서",
            "projectName": "기타",
            "categoriesName": "사업부서_검토_수정",
            "subcategoriesName": "상세_검토수정",
            "subsubcategoriesName": "상세_검토수정",
            "baseTime": "3",
            "spentTime": "5",
            "status": "진행중",
            "note": "산업부신규사업(스마트디지털헬스케어)기획서관련자료조사",
            "remainingTime": "-2",
            "Uesrsid": "XJwp5I5AXb2GhK04cOVN"
        },
        {
            "date": "2024-09-26",
            "userTeam": "통합헬스케어기획팀",
            "userName": "김가인",
            "department": "사업부서",
            "projectName": "기타",
            "categoriesName": "사업부서_검토_수정",
            "subcategoriesName": "상세_검토수정",
            "subsubcategoriesName": "상세_검토수정",
            "baseTime": "3",
            "spentTime": "5",
            "status": "진행중",
            "note": "산업부신규사업(AI슬립테크)기획서관련자료조사",
            "remainingTime": "-2",
            "Uesrsid": "XJwp5I5AXb2GhK04cOVN"
        },
        {
            "date": "2024-09-27",
            "userTeam": "통합헬스케어기획팀",
            "userName": "김가인",
            "department": "사업부서",
            "projectName": "기타",
            "categoriesName": "사업부서_검토_수정",
            "subcategoriesName": "상세_검토수정",
            "subsubcategoriesName": "상세_검토수정",
            "baseTime": "3",
            "spentTime": "5",
            "status": "진행중",
            "note": "산업부신규사업(스마트디지털헬스케어)기획서관련자료조사",
            "remainingTime": "-2",
            "Uesrsid": "XJwp5I5AXb2GhK04cOVN"
        },
        {
            "date": "2024-09-30",
            "userTeam": "통합헬스케어기획팀",
            "userName": "김가인",
            "department": "사업부서",
            "projectName": "기타",
            "categoriesName": "사업부서_검토_수정",
            "subcategoriesName": "상세_검토수정",
            "subsubcategoriesName": "상세_검토수정",
            "baseTime": "3",
            "spentTime": "5",
            "status": "진행중",
            "note": "산업부신규사업(AI슬립테크)기획서관련자료조사",
            "remainingTime": "-2",
            "Uesrsid": "XJwp5I5AXb2GhK04cOVN"
        },
        {
            "date": "2024-10-02",
            "userTeam": "통합헬스케어기획팀",
            "userName": "김가인",
            "department": "사업부서",
            "projectName": "SWMD",
            "categoriesName": "행사운영",
            "subcategoriesName": "행사수행",
            "subsubcategoriesName": "행사운영,관리감독,참석자민원응대,정리등",
            "baseTime": "4",
            "spentTime": "8",
            "status": "진행중",
            "note": "KCR2024전시부스참가",
            "remainingTime": "-4",
            "Uesrsid": "XJwp5I5AXb2GhK04cOVN"
        },
        {
            "date": "2024-10-03",
            "userTeam": "통합헬스케어기획팀",
            "userName": "김가인",
            "department": "사업부서",
            "projectName": "SWMD",
            "categoriesName": "행사운영",
            "subcategoriesName": "행사수행",
            "subsubcategoriesName": "행사운영,관리감독,참석자민원응대,정리등",
            "baseTime": "4",
            "spentTime": "8",
            "status": "진행중",
            "note": "KCR2024전시부스참가",
            "remainingTime": "-4",
            "Uesrsid": "XJwp5I5AXb2GhK04cOVN"
        },
        {
            "date": "2024-10-04",
            "userTeam": "통합헬스케어기획팀",
            "userName": "김가인",
            "department": "사업부서",
            "projectName": "SWMD",
            "categoriesName": "행사운영",
            "subcategoriesName": "행사수행",
            "subsubcategoriesName": "행사운영,관리감독,참석자민원응대,정리등",
            "baseTime": "4",
            "spentTime": "8",
            "status": "완료",
            "note": "KCR2024전시부스참가",
            "remainingTime": "-4",
            "Uesrsid": "XJwp5I5AXb2GhK04cOVN"
        },
        {
            "date": "2024-10-07",
            "userTeam": "통합헬스케어기획팀",
            "userName": "김가인",
            "department": "사업부서",
            "projectName": "SWMD",
            "categoriesName": "전시회",
            "subcategoriesName": "전시회준비",
            "subsubcategoriesName": "전시회참가물품확인(족자봉,브로슈어,홍보물,신문등)",
            "baseTime": "1",
            "spentTime": "8",
            "status": "진행중",
            "note": "MEDICALJAPANTOKYO2024준비",
            "remainingTime": "-7",
            "Uesrsid": "XJwp5I5AXb2GhK04cOVN"
        },
        {
            "date": "2024-10-08",
            "userTeam": "통합헬스케어기획팀",
            "userName": "김가인",
            "department": "사업부서",
            "projectName": "SWMD",
            "categoriesName": "전시회",
            "subcategoriesName": "전시회운영",
            "subsubcategoriesName": "전시회참가",
            "baseTime": "24",
            "spentTime": "8",
            "status": "진행중",
            "note": "MEDICALJAPANTOKYO2024참가",
            "remainingTime": "16",
            "Uesrsid": "XJwp5I5AXb2GhK04cOVN"
        },
        {
            "date": "2024-10-09",
            "userTeam": "통합헬스케어기획팀",
            "userName": "김가인",
            "department": "사업부서",
            "projectName": "SWMD",
            "categoriesName": "전시회",
            "subcategoriesName": "전시회운영",
            "subsubcategoriesName": "전시회참가",
            "baseTime": "24",
            "spentTime": "8",
            "status": "진행중",
            "note": "MEDICALJAPANTOKYO2024참가",
            "remainingTime": "16",
            "Uesrsid": "XJwp5I5AXb2GhK04cOVN"
        },
        {
            "date": "2024-10-10",
            "userTeam": "통합헬스케어기획팀",
            "userName": "김가인",
            "department": "사업부서",
            "projectName": "SWMD",
            "categoriesName": "전시회",
            "subcategoriesName": "전시회운영",
            "subsubcategoriesName": "전시회참가",
            "baseTime": "24",
            "spentTime": "8",
            "status": "진행중",
            "note": "MEDICALJAPANTOKYO2024참가",
            "remainingTime": "16",
            "Uesrsid": "XJwp5I5AXb2GhK04cOVN"
        },
        {
            "date": "2024-10-11",
            "userTeam": "통합헬스케어기획팀",
            "userName": "김가인",
            "department": "사업부서",
            "projectName": "SWMD",
            "categoriesName": "전시회",
            "subcategoriesName": "전시회운영",
            "subsubcategoriesName": "전시회참가",
            "baseTime": "24",
            "spentTime": "8",
            "status": "완료",
            "note": "MEDICALJAPANTOKYO2024참가",
            "remainingTime": "16",
            "Uesrsid": "XJwp5I5AXb2GhK04cOVN"
        },
        {
            "date": "2024-10-14",
            "userTeam": "통합헬스케어기획팀",
            "userName": "김가인",
            "department": "사업부서",
            "projectName": "SWMD",
            "categoriesName": "전시회",
            "subcategoriesName": "전시회_후속작업_결과보고",
            "subsubcategoriesName": "전시회결과보고서작성",
            "baseTime": "4",
            "spentTime": "4",
            "status": "완료",
            "note": "MEDICALJAPANTOKYO2024자료취합및결과보고서초안작성",
            "remainingTime": "0",
            "Uesrsid": "XJwp5I5AXb2GhK04cOVN"
        },
        {
            "date": "2024-10-15",
            "userTeam": "통합헬스케어기획팀",
            "userName": "김가인",
            "department": "사업부서",
            "projectName": "SWMD",
            "categoriesName": "전시회",
            "subcategoriesName": "전시회_후속작업_결과보고",
            "subsubcategoriesName": "전시회결과보고서작성",
            "baseTime": "4",
            "spentTime": "4",
            "status": "완료",
            "note": "MEDICALJAPANTOKYO2024자료취합및결과보고서초안작성",
            "remainingTime": "0",
            "Uesrsid": "XJwp5I5AXb2GhK04cOVN"
        },
        {
            "date": "2024-10-16",
            "userTeam": "통합헬스케어기획팀",
            "userName": "김가인",
            "department": "사업부서",
            "projectName": "SWMD",
            "categoriesName": "전시회",
            "subcategoriesName": "전시회_후속작업_결과보고",
            "subsubcategoriesName": "전시회결과보고서작성",
            "baseTime": "4",
            "spentTime": "4",
            "status": "완료",
            "note": "MEDICALJAPANTOKYO2024자료취합및결과보고서초안작성",
            "remainingTime": "0",
            "Uesrsid": "XJwp5I5AXb2GhK04cOVN"
        },
        {
            "date": "2024-10-17",
            "userTeam": "통합헬스케어기획팀",
            "userName": "김가인",
            "department": "사업부서",
            "projectName": "SWMD",
            "categoriesName": "전시회",
            "subcategoriesName": "전시회_후속작업_결과보고",
            "subsubcategoriesName": "전시회결과보고서작성",
            "baseTime": "4",
            "spentTime": "4",
            "status": "완료",
            "note": "MEDICALJAPANTOKYO2024자료취합및결과보고서초안작성",
            "remainingTime": "0",
            "Uesrsid": "XJwp5I5AXb2GhK04cOVN"
        },
        {
            "date": "2024-10-18",
            "userTeam": "통합헬스케어기획팀",
            "userName": "김가인",
            "department": "사업부서",
            "projectName": "SWMD",
            "categoriesName": "전시회",
            "subcategoriesName": "전시회운영",
            "subsubcategoriesName": "전시회참가",
            "baseTime": "24",
            "spentTime": "8",
            "status": "진행중",
            "note": "KIMESBUSAN2024전시부스참가(전주기통합컨설팅)",
            "remainingTime": "16",
            "Uesrsid": "XJwp5I5AXb2GhK04cOVN"
        },
        {
            "date": "2024-10-19",
            "userTeam": "통합헬스케어기획팀",
            "userName": "김가인",
            "department": "사업부서",
            "projectName": "SWMD",
            "categoriesName": "전시회",
            "subcategoriesName": "전시회운영",
            "subsubcategoriesName": "전시회참가",
            "baseTime": "24",
            "spentTime": "8",
            "status": "진행중",
            "note": "KIMESBUSAN2024전시부스참가(전주기통합컨설팅)",
            "remainingTime": "16",
            "Uesrsid": "XJwp5I5AXb2GhK04cOVN"
        },
        {
            "date": "2024-10-20",
            "userTeam": "통합헬스케어기획팀",
            "userName": "김가인",
            "department": "사업부서",
            "projectName": "SWMD",
            "categoriesName": "전시회",
            "subcategoriesName": "전시회운영",
            "subsubcategoriesName": "전시회참가",
            "baseTime": "24",
            "spentTime": "8",
            "status": "완료",
            "note": "KIMESBUSAN2024전시부스참가(전주기통합컨설팅)",
            "remainingTime": "16",
            "Uesrsid": "XJwp5I5AXb2GhK04cOVN"
        },
        {
            "date": "2024-10-22",
            "userTeam": "통합헬스케어기획팀",
            "userName": "김가인",
            "department": "사업부서",
            "projectName": "한림원용역",
            "categoriesName": "전시회",
            "subcategoriesName": "전시회준비",
            "subsubcategoriesName": "참가계획수립",
            "baseTime": "5",
            "spentTime": "4",
            "status": "진행중",
            "note": "한-베디지털전환포럼'참가계획서초안작성",
            "remainingTime": "1",
            "Uesrsid": "XJwp5I5AXb2GhK04cOVN"
        },
        {
            "date": "2024-10-23",
            "userTeam": "통합헬스케어기획팀",
            "userName": "김가인",
            "department": "사업부서",
            "projectName": "SWMD",
            "categoriesName": "행사운영",
            "subcategoriesName": "행사준비",
            "subsubcategoriesName": "행사자료작성및검토",
            "baseTime": "6",
            "spentTime": "1",
            "status": "완료",
            "note": "소프트웨어의료기기(SaMD)임상시험프로세스교육",
            "remainingTime": "5",
            "Uesrsid": "XJwp5I5AXb2GhK04cOVN"
        },
        {
            "date": "2024-10-24",
            "userTeam": "통합헬스케어기획팀",
            "userName": "김가인",
            "department": "사업부서",
            "projectName": "SWMD",
            "categoriesName": "행사운영",
            "subcategoriesName": "행사수행",
            "subsubcategoriesName": "행사운영,관리감독,참석자민원응대,정리등",
            "baseTime": "4",
            "spentTime": "8",
            "status": "완료",
            "note": "소프트웨어의료기기(SaMD)임상시험프로세스교육운영",
            "remainingTime": "-4",
            "Uesrsid": "XJwp5I5AXb2GhK04cOVN"
        },
        {
            "date": "2024-10-28",
            "userTeam": "통합헬스케어기획팀",
            "userName": "김가인",
            "department": "사업부서",
            "projectName": "한림원용역",
            "categoriesName": "전시회",
            "subcategoriesName": "전시회준비",
            "subsubcategoriesName": "참가계획수립",
            "baseTime": "5",
            "spentTime": "4",
            "status": "진행중",
            "note": "한-베디지털전환포럼'참가계획관련nipa자료검토",
            "remainingTime": "1",
            "Uesrsid": "XJwp5I5AXb2GhK04cOVN"
        },
        {
            "date": "2024-10-29",
            "userTeam": "통합헬스케어기획팀",
            "userName": "김가인",
            "department": "사업부서",
            "projectName": "SWMD",
            "categoriesName": "행사운영",
            "subcategoriesName": "행사수행",
            "subsubcategoriesName": "행사운영,관리감독,참석자민원응대,정리등",
            "baseTime": "4",
            "spentTime": "8",
            "status": "진행중",
            "note": "소프트웨어의료기기(SaMD)FDA인허가프로세스교육운영",
            "remainingTime": "-4",
            "Uesrsid": "XJwp5I5AXb2GhK04cOVN"
        },
        {
            "date": "2024-10-30",
            "userTeam": "통합헬스케어기획팀",
            "userName": "김가인",
            "department": "사업부서",
            "projectName": "SWMD",
            "categoriesName": "행사운영",
            "subcategoriesName": "행사수행",
            "subsubcategoriesName": "행사운영,관리감독,참석자민원응대,정리등",
            "baseTime": "4",
            "spentTime": "8",
            "status": "완료",
            "note": "소프트웨어의료기기(SaMD)FDA인허가프로세스교육운영",
            "remainingTime": "-4",
            "Uesrsid": "XJwp5I5AXb2GhK04cOVN"
        },
        {
            "date": "2024-10-31",
            "userTeam": "통합헬스케어기획팀",
            "userName": "김가인",
            "department": "사업부서",
            "projectName": "SWMD",
            "categoriesName": "행사운영",
            "subcategoriesName": "행사_후속작업_결과보고",
            "subsubcategoriesName": "행사운영결과보고(증빙취합시간제외)",
            "baseTime": "4",
            "spentTime": "4",
            "status": "완료",
            "note": "소프트웨어의료기기(SaMD)FDA인허가프로세스교육결과보고초안작성",
            "remainingTime": "0",
            "Uesrsid": "XJwp5I5AXb2GhK04cOVN"
        },
        {
            "date": "2024-11-01",
            "userTeam": "통합헬스케어기획팀",
            "userName": "김가인",
            "department": "사업부서",
            "projectName": "한림원용역",
            "categoriesName": "전시회",
            "subcategoriesName": "전시회준비",
            "subsubcategoriesName": "부스및설치가구류계약",
            "baseTime": "2",
            "spentTime": "3",
            "status": "진행중",
            "note": "한-베디지털전환포럼'부스인테리어및기업참석자취합",
            "remainingTime": "-1",
            "Uesrsid": "XJwp5I5AXb2GhK04cOVN"
        },
        {
            "date": "2024-11-04",
            "userTeam": "통합헬스케어기획팀",
            "userName": "김가인",
            "department": "사업부서",
            "projectName": "한림원용역",
            "categoriesName": "전시회",
            "subcategoriesName": "전시회준비",
            "subsubcategoriesName": "교통및숙박인원확정",
            "baseTime": "2",
            "spentTime": "3",
            "status": "진행중",
            "note": "한-베디지털전환포럼'부스기업참석자확정",
            "remainingTime": "-1",
            "Uesrsid": "XJwp5I5AXb2GhK04cOVN"
        },
        {
            "date": "2024-11-05",
            "userTeam": "통합헬스케어기획팀",
            "userName": "김가인",
            "department": "사업부서",
            "projectName": "한림원용역",
            "categoriesName": "전시회",
            "subcategoriesName": "전시회준비",
            "subsubcategoriesName": "전시회참가물품확인(족자봉,브로슈어,홍보물,신문등)",
            "baseTime": "1",
            "spentTime": "3",
            "status": "진행중",
            "note": "한-베디지털전환포럼'기업브로셔제작검토",
            "remainingTime": "-2",
            "Uesrsid": "XJwp5I5AXb2GhK04cOVN"
        },
        {
            "date": "2024-11-06",
            "userTeam": "통합헬스케어기획팀",
            "userName": "김가인",
            "department": "사업부서",
            "projectName": "SWMD",
            "categoriesName": "사업부서_기타",
            "subcategoriesName": "협회기타",
            "subsubcategoriesName": "협회기타(자리이동,청소,주간회의등)",
            "baseTime": "1",
            "spentTime": "6",
            "status": "완료",
            "note": "2024ICTR&D주간세미나참석",
            "remainingTime": "-5",
            "Uesrsid": "XJwp5I5AXb2GhK04cOVN"
        },
        {
            "date": "2024-11-11",
            "userTeam": "통합헬스케어기획팀",
            "userName": "김가인",
            "department": "사업부서",
            "projectName": "한림원용역",
            "categoriesName": "전시회",
            "subcategoriesName": "전시회준비",
            "subsubcategoriesName": "전시회참가물품확인(족자봉,브로슈어,홍보물,신문등)",
            "baseTime": "1",
            "spentTime": "2",
            "status": "진행중",
            "note": "한-베디지털전환포럼'기업브로셔확정및인쇄의뢰",
            "remainingTime": "-1",
            "Uesrsid": "XJwp5I5AXb2GhK04cOVN"
        },
        {
            "date": "2024-11-12",
            "userTeam": "통합헬스케어기획팀",
            "userName": "김가인",
            "department": "사업부서",
            "projectName": "한림원용역",
            "categoriesName": "전시회",
            "subcategoriesName": "전시회준비",
            "subsubcategoriesName": "전시회계획보고서작성(견적서작업포함)",
            "baseTime": "3",
            "spentTime": "3",
            "status": "진행중",
            "note": "용역계약서작성(VLOOKG,42INTERNATIONAL)",
            "remainingTime": "0",
            "Uesrsid": "XJwp5I5AXb2GhK04cOVN"
        },
        {
            "date": "2024-11-13",
            "userTeam": "통합헬스케어기획팀",
            "userName": "김가인",
            "department": "사업부서",
            "projectName": "한림원용역",
            "categoriesName": "전시회",
            "subcategoriesName": "전시회준비",
            "subsubcategoriesName": "전시회계획보고서작성(견적서작업포함)",
            "baseTime": "3",
            "spentTime": "3",
            "status": "진행중",
            "note": "용역계약서작성(VLOOKG,42INTERNATIONAL)",
            "remainingTime": "0",
            "Uesrsid": "XJwp5I5AXb2GhK04cOVN"
        },
        {
            "date": "2024-11-14",
            "userTeam": "통합헬스케어기획팀",
            "userName": "김가인",
            "department": "사업부서",
            "projectName": "한림원용역",
            "categoriesName": "전시회",
            "subcategoriesName": "전시회준비",
            "subsubcategoriesName": "참가계획수립",
            "baseTime": "5",
            "spentTime": "3",
            "status": "진행중",
            "note": "호찌민일정수립",
            "remainingTime": "2",
            "Uesrsid": "XJwp5I5AXb2GhK04cOVN"
        },
        {
            "date": "2024-11-15",
            "userTeam": "통합헬스케어기획팀",
            "userName": "김가인",
            "department": "사업부서",
            "projectName": "한림원용역",
            "categoriesName": "전시회",
            "subcategoriesName": "전시회준비",
            "subsubcategoriesName": "참가계획수립",
            "baseTime": "5",
            "spentTime": "3",
            "status": "진행중",
            "note": "하노이일정수립",
            "remainingTime": "2",
            "Uesrsid": "XJwp5I5AXb2GhK04cOVN"
        },
        {
            "date": "2024-11-18",
            "userTeam": "통합헬스케어기획팀",
            "userName": "김가인",
            "department": "사업부서",
            "projectName": "SWMD",
            "categoriesName": "행사운영",
            "subcategoriesName": "행사준비",
            "subsubcategoriesName": "행사자료작성및검토",
            "baseTime": "6",
            "spentTime": "4",
            "status": "완료",
            "note": "식품의약품안전처디지털의료제품법정책설명회(광주)계획보고서초안작성",
            "remainingTime": "2",
            "Uesrsid": "XJwp5I5AXb2GhK04cOVN"
        },
        {
            "date": "2024-11-19",
            "userTeam": "통합헬스케어기획팀",
            "userName": "김가인",
            "department": "사업부서",
            "projectName": "SWMD",
            "categoriesName": "행사운영",
            "subcategoriesName": "행사준비",
            "subsubcategoriesName": "행사운영계획보고서작성(견적서작업포함)",
            "baseTime": "3",
            "spentTime": "4",
            "status": "완료",
            "note": "식품의약품안전처디지털의료제품법정책설명회(광주)계획보고서초안작성",
            "remainingTime": "-1",
            "Uesrsid": "XJwp5I5AXb2GhK04cOVN"
        },
        {
            "date": "2024-11-20",
            "userTeam": "통합헬스케어기획팀",
            "userName": "김가인",
            "department": "사업부서",
            "projectName": "SWMD",
            "categoriesName": "행사운영",
            "subcategoriesName": "행사준비",
            "subsubcategoriesName": "행사개최계획수립",
            "baseTime": "2",
            "spentTime": "4",
            "status": "완료",
            "note": "식품의약품안전처디지털의료제품법정책설명회(광주)계획보고서초안작성",
            "remainingTime": "-2",
            "Uesrsid": "XJwp5I5AXb2GhK04cOVN"
        },
        {
            "date": "2024-11-22",
            "userTeam": "통합헬스케어기획팀",
            "userName": "김가인",
            "department": "사업부서",
            "projectName": "SWMD",
            "categoriesName": "행사운영",
            "subcategoriesName": "행사준비",
            "subsubcategoriesName": "행사자료인쇄물(현수막,x배너,책자,명찰등)확인",
            "baseTime": "2",
            "spentTime": "4",
            "status": "완료",
            "note": "식품의약품안전처디지털의료제품법정책설명회(광주)준비",
            "remainingTime": "-2",
            "Uesrsid": "XJwp5I5AXb2GhK04cOVN"
        },
        {
            "date": "2024-11-25",
            "userTeam": "통합헬스케어기획팀",
            "userName": "김가인",
            "department": "사업부서",
            "projectName": "한림원용역",
            "categoriesName": "회의운영",
            "subcategoriesName": "외부회의",
            "subsubcategoriesName": "회의진행(출장시출장이동시간포함)",
            "baseTime": "2",
            "spentTime": "6",
            "status": "완료",
            "note": "'의료AI기업해외진출지원연구사업'nipa방향성자문회의",
            "remainingTime": "-4",
            "Uesrsid": "XJwp5I5AXb2GhK04cOVN"
        },
        {
            "date": "2024-11-26",
            "userTeam": "통합헬스케어기획팀",
            "userName": "김가인",
            "department": "사업부서",
            "projectName": "SWMD",
            "categoriesName": "사업부서_기타",
            "subcategoriesName": "협회기타",
            "subsubcategoriesName": "협회기타(자리이동,청소,주간회의등)",
            "baseTime": "1",
            "spentTime": "3",
            "status": "진행중",
            "note": "디지털의료제품법설명회(서울)행사장사전점검",
            "remainingTime": "-2",
            "Uesrsid": "XJwp5I5AXb2GhK04cOVN"
        },
        {
            "date": "2024-11-27",
            "userTeam": "통합헬스케어기획팀",
            "userName": "김가인",
            "department": "사업부서",
            "projectName": "SWMD",
            "categoriesName": "사업부서_검토_수정",
            "subcategoriesName": "간단_검토수정",
            "subsubcategoriesName": "간단_검토수정",
            "baseTime": "1",
            "spentTime": "4",
            "status": "진행중",
            "note": "식품의약품안전처디지털의료제품법정책설명회(서울)행사현수막명찰등준비",
            "remainingTime": "-3",
            "Uesrsid": "XJwp5I5AXb2GhK04cOVN"
        },
        {
            "date": "2024-11-28",
            "userTeam": "통합헬스케어기획팀",
            "userName": "김가인",
            "department": "사업부서",
            "projectName": "한림원용역",
            "categoriesName": "행정",
            "subcategoriesName": "경비_지출",
            "subsubcategoriesName": "결제건관련증빙서류확인및취합-단순지출증빙일경우",
            "baseTime": "0.1",
            "spentTime": "4",
            "status": "완료",
            "note": "회의비영수증취합및회의록준비",
            "remainingTime": "-3.9",
            "Uesrsid": "XJwp5I5AXb2GhK04cOVN"
        },
        {
            "date": "2024-11-29",
            "userTeam": "통합헬스케어기획팀",
            "userName": "김가인",
            "department": "사업부서",
            "projectName": "SWMD",
            "categoriesName": "행사운영",
            "subcategoriesName": "행사준비",
            "subsubcategoriesName": "행사자료작성및검토",
            "baseTime": "6",
            "spentTime": "6",
            "status": "완료",
            "note": "RSNA2024학회참석준비및등록확인",
            "remainingTime": "0",
            "Uesrsid": "XJwp5I5AXb2GhK04cOVN"
        },
        {
            "date": "2024-11-30",
            "userTeam": "통합헬스케어기획팀",
            "userName": "김가인",
            "department": "사업부서",
            "projectName": "SWMD",
            "categoriesName": "전시회",
            "subcategoriesName": "전시회운영",
            "subsubcategoriesName": "전시회참가",
            "baseTime": "24",
            "spentTime": "8",
            "status": "진행중",
            "note": "RSNA2024학회참석",
            "remainingTime": "16",
            "Uesrsid": "XJwp5I5AXb2GhK04cOVN"
        },
        {
            "date": "2024-12-01",
            "userTeam": "통합헬스케어기획팀",
            "userName": "김가인",
            "department": "사업부서",
            "projectName": "SWMD",
            "categoriesName": "전시회",
            "subcategoriesName": "전시회운영",
            "subsubcategoriesName": "전시회참가",
            "baseTime": "24",
            "spentTime": "8",
            "status": "진행중",
            "note": "RSNA2024학회참석",
            "remainingTime": "16",
            "Uesrsid": "XJwp5I5AXb2GhK04cOVN"
        },
        {
            "date": "2024-12-02",
            "userTeam": "통합헬스케어기획팀",
            "userName": "김가인",
            "department": "사업부서",
            "projectName": "SWMD",
            "categoriesName": "전시회",
            "subcategoriesName": "전시회운영",
            "subsubcategoriesName": "전시회참가",
            "baseTime": "24",
            "spentTime": "8",
            "status": "진행중",
            "note": "RSNA2024학회참석",
            "remainingTime": "16",
            "Uesrsid": "XJwp5I5AXb2GhK04cOVN"
        },
        {
            "date": "2024-12-03",
            "userTeam": "통합헬스케어기획팀",
            "userName": "김가인",
            "department": "사업부서",
            "projectName": "SWMD",
            "categoriesName": "전시회",
            "subcategoriesName": "전시회운영",
            "subsubcategoriesName": "전시회참가",
            "baseTime": "24",
            "spentTime": "8",
            "status": "진행중",
            "note": "RSNA2024학회참석",
            "remainingTime": "16",
            "Uesrsid": "XJwp5I5AXb2GhK04cOVN"
        },
        {
            "date": "2024-12-04",
            "userTeam": "통합헬스케어기획팀",
            "userName": "김가인",
            "department": "사업부서",
            "projectName": "SWMD",
            "categoriesName": "전시회",
            "subcategoriesName": "전시회운영",
            "subsubcategoriesName": "전시회참가",
            "baseTime": "24",
            "spentTime": "8",
            "status": "진행중",
            "note": "RSNA2024학회참석",
            "remainingTime": "16",
            "Uesrsid": "XJwp5I5AXb2GhK04cOVN"
        },
        {
            "date": "2024-12-05",
            "userTeam": "통합헬스케어기획팀",
            "userName": "김가인",
            "department": "사업부서",
            "projectName": "SWMD",
            "categoriesName": "전시회",
            "subcategoriesName": "전시회운영",
            "subsubcategoriesName": "전시회참가",
            "baseTime": "24",
            "spentTime": "8",
            "status": "진행중",
            "note": "RSNA2024학회참석",
            "remainingTime": "16",
            "Uesrsid": "XJwp5I5AXb2GhK04cOVN"
        },
        {
            "date": "2024-12-06",
            "userTeam": "통합헬스케어기획팀",
            "userName": "김가인",
            "department": "사업부서",
            "projectName": "SWMD",
            "categoriesName": "전시회",
            "subcategoriesName": "전시회운영",
            "subsubcategoriesName": "전시회참가",
            "baseTime": "24",
            "spentTime": "8",
            "status": "완료",
            "note": "RSNA2024학회참석",
            "remainingTime": "16",
            "Uesrsid": "XJwp5I5AXb2GhK04cOVN"
        },
        {
            "date": "2024-12-09",
            "userTeam": "통합헬스케어기획팀",
            "userName": "김가인",
            "department": "사업부서",
            "projectName": "기타",
            "categoriesName": "행사운영",
            "subcategoriesName": "행사준비",
            "subsubcategoriesName": "행사자료작성및검토",
            "baseTime": "6",
            "spentTime": "4",
            "status": "완료",
            "note": "산업부권역별병원협의체준비",
            "remainingTime": "2",
            "Uesrsid": "XJwp5I5AXb2GhK04cOVN"
        },
        {
            "date": "2024-12-11",
            "userTeam": "통합헬스케어기획팀",
            "userName": "김가인",
            "department": "사업부서",
            "projectName": "SWMD",
            "categoriesName": "행사운영",
            "subcategoriesName": "행사수행",
            "subsubcategoriesName": "행사운영,관리감독,참석자민원응대,정리등",
            "baseTime": "4",
            "spentTime": "5",
            "status": "완료",
            "note": "소프트웨어의료기기(SaMD)국내인허가교육운영",
            "remainingTime": "-1",
            "Uesrsid": "XJwp5I5AXb2GhK04cOVN"
        },
        {
            "date": "2024-12-12",
            "userTeam": "통합헬스케어기획팀",
            "userName": "김가인",
            "department": "사업부서",
            "projectName": "기타",
            "categoriesName": "행사운영",
            "subcategoriesName": "행사준비",
            "subsubcategoriesName": "행사자료작성및검토",
            "baseTime": "6",
            "spentTime": "3",
            "status": "완료",
            "note": "산업부권역별병원협의체행사준비",
            "remainingTime": "3",
            "Uesrsid": "XJwp5I5AXb2GhK04cOVN"
        },
        {
            "date": "2024-12-13",
            "userTeam": "통합헬스케어기획팀",
            "userName": "김가인",
            "department": "사업부서",
            "projectName": "SWMD",
            "categoriesName": "행사운영",
            "subcategoriesName": "행사_후속작업_결과보고",
            "subsubcategoriesName": "행사운영결과보고(증빙취합시간제외)",
            "baseTime": "4",
            "spentTime": "6",
            "status": "진행중",
            "note": "MEDICALJAPANTOKYO2024결과보고서작성",
            "remainingTime": "-2",
            "Uesrsid": "XJwp5I5AXb2GhK04cOVN"
        },
        {
            "date": "2024-12-16",
            "userTeam": "통합헬스케어기획팀",
            "userName": "김가인",
            "department": "사업부서",
            "projectName": "기타",
            "categoriesName": "행사운영",
            "subcategoriesName": "행사수행",
            "subsubcategoriesName": "행사운영,관리감독,참석자민원응대,정리등",
            "baseTime": "4",
            "spentTime": "8",
            "status": "완료",
            "note": "소프트웨어의료기기권역별병원협의체",
            "remainingTime": "-4",
            "Uesrsid": "XJwp5I5AXb2GhK04cOVN"
        },
        {
            "date": "2024-12-17",
            "userTeam": "통합헬스케어기획팀",
            "userName": "김가인",
            "department": "사업부서",
            "projectName": "한림원용역",
            "categoriesName": "행정",
            "subcategoriesName": "회의록_업무추진비",
            "subsubcategoriesName": "회의록작성",
            "baseTime": "1",
            "spentTime": "5",
            "status": "진행중",
            "note": "회의록취합및지출결의입력준비",
            "remainingTime": "-4",
            "Uesrsid": "XJwp5I5AXb2GhK04cOVN"
        },
        {
            "date": "2024-12-18",
            "userTeam": "통합헬스케어기획팀",
            "userName": "김가인",
            "department": "사업부서",
            "projectName": "SWMD",
            "categoriesName": "행사운영",
            "subcategoriesName": "행사준비",
            "subsubcategoriesName": "행사자료작성및검토",
            "baseTime": "6",
            "spentTime": "4",
            "status": "완료",
            "note": "식품의약품안전처디지털의료제품법정책설명회(서울)준비",
            "remainingTime": "2",
            "Uesrsid": "XJwp5I5AXb2GhK04cOVN"
        },
        {
            "date": "2024-12-24",
            "userTeam": "통합헬스케어기획팀",
            "userName": "김가인",
            "department": "사업부서",
            "projectName": "SWMD",
            "categoriesName": "행정",
            "subcategoriesName": "문서기안",
            "subsubcategoriesName": "출장보고서",
            "baseTime": "0.5",
            "spentTime": "5",
            "status": "진행중",
            "remainingTime": "-4.5",
            "Uesrsid": "XJwp5I5AXb2GhK04cOVN"
        },
        {
            "date": "2024-12-26",
            "userTeam": "통합헬스케어기획팀",
            "userName": "김가인",
            "department": "사업부서",
            "projectName": "SWMD",
            "categoriesName": "행정",
            "subcategoriesName": "문서기안",
            "subsubcategoriesName": "시행문,공문",
            "baseTime": "1",
            "spentTime": "1",
            "status": "완료",
            "note": "한림원용역잔금지급신청",
            "remainingTime": "1",
            "Uesrsid": "XJwp5I5AXb2GhK04cOVN"
        },
        {
            "date": "2024-12-27",
            "userTeam": "통합헬스케어기획팀",
            "userName": "김가인",
            "department": "사업부서",
            "projectName": "한림원용역",
            "categoriesName": "행사운영",
            "subcategoriesName": "행사수행",
            "subsubcategoriesName": "행사운영,관리감독,참석자민원응대,정리등",
            "baseTime": "4",
            "spentTime": "6",
            "status": "완료",
            "note": "의료AI기업해외진출성공전략컨퍼런스",
            "remainingTime": "-2",
            "Uesrsid": "XJwp5I5AXb2GhK04cOVN"
        }
    ];

    // Firestore에 데이터를 추가하는 함수
    const addTaskData = async () => {
        try {
            const db = firebase.firestore(); // Firestore 인스턴스 가져오기
            const tasksCollection = db.collection('tasks'); // 'tasks' 컬렉션 참조

            for (const task of taskData) {
                // Firestore에 문서 추가 (문서 ID는 자동 생성)
                await tasksCollection.add(task);
            }

            console.log('Task data added successfully!');
        } catch (error) {
            console.error('Error adding task data:', error);
        }
    };

    return (
        <div className="add-task-container">
            <button className="add-task-button" onClick={addTaskData}>
                Add Task
            </button>
        </div>
    );
}

export default AddLegoData;
